-- Life OS database schema
--
-- The schema is managed exclusively by the ordered files in
-- `supabase/migrations/`. Use the Supabase CLI migration workflow instead of
-- running a standalone schema script so that account ownership, Row Level
-- Security policies, storage rules, and data migrations stay in sync.
--
-- The current private-account model is introduced by:
--   migrations/20260814163629_private_user_accounts.sql
