-- 0005_lifeos_prompt_seed.sql
--
-- The 365 question rotation for the daily prompt.
--
-- day_index 0 is PROMPT_EPOCH (2026-01-01) in Asia/Dubai; see
-- promptIndexFor() in src/lifeos/prompts.ts. The cycle repeats after 365
-- days, so year two asks the same questions in the same order. That is
-- intentional: the answers will not be the same.
--
-- Editing a question in place changes it for future years but leaves past
-- answers attached to their date, which is what you want.
--
-- Requires 0004_lifeos_prompts.sql.

insert into public.lifeos_prompts (day_index, text) values
  (0, 'What did you notice today that nobody else would have?'),
  (1, 'What is something you changed your mind about this year?'),
  (2, 'Describe the last thing that made you laugh out loud, properly.'),
  (3, 'What is a small thing I do that you would miss if I stopped?'),
  (4, 'What were you like at fifteen?'),
  (5, 'What is the most useless thing you know a lot about?'),
  (6, 'What did today taste like?'),
  (7, 'What is something you are avoiding right now?'),
  (8, 'If you had a free Tuesday with no obligations, what would actually happen?'),
  (9, 'What is a compliment you received that you still think about?'),
  (10, 'What is the worst advice you have ever been given?'),
  (11, 'Which of your parents are you more like, and does that bother you?'),
  (12, 'What did you want to be when you were nine?'),
  (13, 'What is something you own that you would replace immediately if it broke?'),
  (14, 'What is the last thing you did purely because you wanted to?'),
  (15, 'Describe your ideal ordinary evening. Not a special one.'),
  (16, 'What is a fear you have that you know is irrational?'),
  (17, 'What is the kindest thing a stranger has done for you?'),
  (18, 'What song can you not listen to anymore, and why?'),
  (19, 'What is something you believed as a child that took embarrassingly long to unlearn?'),
  (20, 'What is the hardest part of this week, honestly?'),
  (21, 'What do you do when nobody is watching that you would be slightly embarrassed about?'),
  (22, 'What is a place you miss that no longer exists the way you remember it?'),
  (23, 'What is your most irrational food opinion?'),
  (24, 'When did you last feel genuinely proud of yourself?'),
  (25, 'What is something you want me to ask you about more often?'),
  (26, 'What is the last risk you took?'),
  (27, 'Who did you used to be close to and are not anymore?'),
  (28, 'What is a smell that takes you straight back somewhere?'),
  (29, 'What would you do with a completely free year?'),
  (30, 'What do you think I do not understand about your day to day?'),
  (31, 'What is the most beautiful thing you saw this week?'),
  (32, 'What is something you are secretly quite good at?'),
  (33, 'What did you argue about most as a kid?'),
  (34, 'What is a habit you have picked up from me?'),
  (35, 'If money were not a factor, where would we live?'),
  (36, 'What is the last thing that genuinely surprised you?'),
  (37, 'What do you think you will care about in ten years that you do not care about now?'),
  (38, 'What is your relationship with your phone right now?'),
  (39, 'What is the loneliest you have ever felt?'),
  (40, 'What is something small you are looking forward to this week?'),
  (41, 'What is a rule you grew up with that you have dropped?'),
  (42, 'Describe the room you are in without looking up.'),
  (43, 'What is the last book, show or song that actually changed something for you?'),
  (44, 'What is a conversation you keep meaning to have?'),
  (45, 'What do you think is the best thing about the way we handle disagreements?'),
  (46, 'What is the worst haircut you have ever had?'),
  (47, 'What are you tired of explaining to people?'),
  (48, 'What is a talent you wish you had?'),
  (49, 'What is something you have forgiven yourself for?'),
  (50, 'What is the most money you have ever spent on something stupid?'),
  (51, 'What do you find genuinely relaxing, as opposed to just distracting?'),
  (52, 'What is something you have never told me because it never came up?'),
  (53, 'What was the best meal of your life?'),
  (54, 'What are you jealous of, if you are honest?'),
  (55, 'What is a version of your life you sometimes imagine?'),
  (56, 'What is the nicest thing about being alone?'),
  (57, 'What do you want more of in the next month?'),
  (58, 'What is something you are dreading?'),
  (59, 'Who is a person you think about often but rarely mention?'),
  (60, 'What is your earliest memory?'),
  (61, 'What would you tell yourself five years ago, and would you have listened?'),
  (62, 'What is a small luxury you refuse to give up?'),
  (63, 'Describe me to someone who has never met me.'),
  (64, 'What is something you find beautiful that most people find boring?'),
  (65, 'When did you last cry, and what about?'),
  (66, 'What is a decision you are glad you made?'),
  (67, 'What do you like about the city you are in right now?'),
  (68, 'What do you hate about the city you are in right now?'),
  (69, 'What is the last kind thing you did that nobody noticed?'),
  (70, 'What did you think love would be like, before?'),
  (71, 'What is your most used app, and how do you feel about that?'),
  (72, 'What is a family story that gets retold every time?'),
  (73, 'What is something you want to be better at, and are you actually going to try?'),
  (74, 'What is the best thing you have eaten this week?'),
  (75, 'What is a piece of clothing you have had for years?'),
  (76, 'What do you think I worry about too much?'),
  (77, 'What is a moment from this year you keep returning to?'),
  (78, 'What is something we should stop doing?'),
  (79, 'What is your favourite thing about your own face?'),
  (80, 'What is a compliment you find hard to accept?'),
  (81, 'What is the last thing that made you angry, properly angry?'),
  (82, 'What is a job you would be terrible at?'),
  (83, 'What do you do first when you get home?'),
  (84, 'What is a small thing that ruins your day?'),
  (85, 'What is a small thing that saves your day?'),
  (86, 'What do you think we are good at together?'),
  (87, 'What is something you have changed about yourself deliberately?'),
  (88, 'What is the strangest thing you find comforting?'),
  (89, 'What is a memory of us that you would keep if you could only keep one?'),
  (90, 'What did you think about in the shower this morning?'),
  (91, 'What is an opinion you hold that most people you know disagree with?'),
  (92, 'What is something you have been putting off for more than a year?'),
  (93, 'Which of your friends would you call at three in the morning?'),
  (94, 'What is the most homesick you have ever felt?'),
  (95, 'What is something that is much harder than people assume?'),
  (96, 'What do you look forward to about seeing me?'),
  (97, 'What is a habit you would like to break?'),
  (98, 'What did you learn this week?'),
  (99, 'What is a thing you own with a story behind it?'),
  (100, 'What is the last photo you took, and why?'),
  (101, 'What is something you are curious about lately?'),
  (102, 'What would your perfect Saturday morning look like?'),
  (103, 'What is an apology you owe someone?'),
  (104, 'What is an apology you are owed?'),
  (105, 'What is a word you overuse?'),
  (106, 'What is something you find genuinely funny that others do not?'),
  (107, 'Who was your first real friend?'),
  (108, 'What is the best decision you made this year?'),
  (109, 'What is a physical sensation you love?'),
  (110, 'What did you get in trouble for as a child?'),
  (111, 'What is a skill you have that surprises people?'),
  (112, 'What do you notice first about a room?'),
  (113, 'What is something you have been wrong about recently?'),
  (114, 'What is your favourite way to waste time?'),
  (115, 'What is a plan of ours you think about most?'),
  (116, 'What is something that used to matter to you and does not anymore?'),
  (117, 'What is the most peaceful place you have ever been?'),
  (118, 'What do you want people to say about you?'),
  (119, 'What is a thing you say that you got from your mother or father?'),
  (120, 'What is the last thing you cooked?'),
  (121, 'What is a small act of rebellion you commit regularly?'),
  (122, 'What is something about your body you have made peace with?'),
  (123, 'What is a question you wish people asked you?'),
  (124, 'What is the longest you have gone without sleep, and why?'),
  (125, 'What is something you are grateful for that is quite specific?'),
  (126, 'What is a thing you find embarrassing about your past self, fondly?'),
  (127, 'If we had a spare room, what would it be for?'),
  (128, 'What is the last favour someone did you?'),
  (129, 'What is something you are protective of?'),
  (130, 'What is your relationship with mornings?'),
  (131, 'What is a fight we had that you learned something from?'),
  (132, 'What is the most alive you have felt?'),
  (133, 'What is a thing you pretend to like?'),
  (134, 'What is a thing you pretend not to like?'),
  (135, 'What is something you want to do in the next five years that you have not told anyone?'),
  (136, 'Describe your commute.'),
  (137, 'What is a thing you always have in your bag?'),
  (138, 'What is the last thing you threw away that you hesitated over?'),
  (139, 'What is a compliment you would like to give me but feel awkward saying out loud?'),
  (140, 'What is the weather doing where you are, and how does it make you feel?'),
  (141, 'What is the best thing about being the age you are?'),
  (142, 'What is a tradition you want us to have?'),
  (143, 'What is something you find difficult to ask for?'),
  (144, 'What is a sound you love?'),
  (145, 'What is a sound you cannot stand?'),
  (146, 'What did your childhood home smell like?'),
  (147, 'What is something you have kept from a previous version of your life?'),
  (148, 'What is a mistake you would make again?'),
  (149, 'What is the most useful thing anyone ever taught you?'),
  (150, 'What is on your mind that you have not said out loud yet?'),
  (151, 'What is a place you want to go that I have never mentioned?'),
  (152, 'What is something you have gotten better at without noticing?'),
  (153, 'What is the last thing you read that stayed with you?'),
  (154, 'What is your honest opinion of how we handle money?'),
  (155, 'What is a thing about me you found strange at first?'),
  (156, 'What are you looking forward to that is more than a year away?'),
  (157, 'What is a way you have changed since we met?'),
  (158, 'What is your idea of a good argument?'),
  (159, 'What is a small kindness you were shown recently?'),
  (160, 'What do you do when you cannot sleep?'),
  (161, 'What is a thing you have never been able to do?'),
  (162, 'What is the last thing that made you feel young?'),
  (163, 'What is the last thing that made you feel old?'),
  (164, 'What is a possession you would grab in a fire?'),
  (165, 'What is something you find hard about being far apart?'),
  (166, 'What is something that is unexpectedly easier about being far apart?'),
  (167, 'What is your favourite time of day, and why?'),
  (168, 'What is a piece of advice you actually took?'),
  (169, 'What do you think your life looks like from the outside?'),
  (170, 'What is something you do that you know annoys me?'),
  (171, 'What is something I do that you have quietly gotten used to?'),
  (172, 'What was the last thing you celebrated?'),
  (173, 'What is a food you could eat every day?'),
  (174, 'What is a thing you were sure about at twenty that you are not sure about now?'),
  (175, 'What is the most spontaneous thing you have ever done?'),
  (176, 'What is something you have been carrying that you could put down?'),
  (177, 'Who do you miss?'),
  (178, 'What is a photo of us you think about?'),
  (179, 'What is a way you like to be looked after when you are ill?'),
  (180, 'What is a thing you find genuinely hard to talk about?'),
  (181, 'What is the last new thing you tried?'),
  (182, 'What is a place in your day where you feel most yourself?'),
  (183, 'What is something you have been generous about lately?'),
  (184, 'What is a promise you made to yourself?'),
  (185, 'What is the strangest job you would consider doing?'),
  (186, 'What is something you like about your work?'),
  (187, 'What is something you would change about your work tomorrow?'),
  (188, 'What is a small thing that would make this week better?'),
  (189, 'What is something you saw recently that you wanted to show me?'),
  (190, 'What is a habit of ours you hope we keep?'),
  (191, 'What did you believe about relationships that turned out to be wrong?'),
  (192, 'What is the last thing you fixed?'),
  (193, 'What is a sentence someone said to you that you never forgot?'),
  (194, 'What is a way you show love that people miss?'),
  (195, 'What is a way I show love that took you a while to notice?'),
  (196, 'What are you saving for?'),
  (197, 'What is a thing you have done that scared you at the time?'),
  (198, 'What is the quietest place you know?'),
  (199, 'What is something you would like to be asked at the end of a bad day?'),
  (200, 'What is your relationship with being alone in public?'),
  (201, 'What is a small thing you have gotten precious about?'),
  (202, 'What is the best gift you have ever received?'),
  (203, 'What is the best gift you have ever given?'),
  (204, 'What is a subject you could talk about for an hour without preparing?'),
  (205, 'What is something you find boring that everyone else seems to love?'),
  (206, 'What is the last thing you did that took real patience?'),
  (207, 'What is a version of us five years from now that you would be happy with?'),
  (208, 'What is a thing about your family you appreciate more now?'),
  (209, 'What is a thing about your family you understand less now?'),
  (210, 'What did you do today that was just for you?'),
  (211, 'What is something you have been meaning to tell me about your week?'),
  (212, 'What is a small decision you agonised over recently?'),
  (213, 'What is a place we should go back to?'),
  (214, 'What is something you find attractive that has nothing to do with looks?'),
  (215, 'What is a way you would like to be surprised?'),
  (216, 'What is the most tired you have been this month?'),
  (217, 'What do you do to feel better that actually works?'),
  (218, 'What do you do to feel better that does not work?'),
  (219, 'What is a rule you have for yourself?'),
  (220, 'What did you notice about me the first time we met?'),
  (221, 'What is a small talent you are proud of?'),
  (222, 'What is a thing you would tell a younger sibling, real or imagined?'),
  (223, 'What is a way this year has been different from what you expected?'),
  (224, 'What is something you have said no to recently?'),
  (225, 'What is something you should have said no to?'),
  (226, 'What is a thing you always notice in other people?'),
  (227, 'What is the nicest thing about your street?'),
  (228, 'What is something you have gotten used to that you should not have?'),
  (229, 'What is a small thing you would like more of from me?'),
  (230, 'What is a good thing that happened today, even if it was small?'),
  (231, 'What is a thing you keep meaning to buy and never do?'),
  (232, 'What is a way your taste has changed?'),
  (233, 'What is the last thing you finished?'),
  (234, 'What is the last thing you abandoned halfway?'),
  (235, 'What is a place you feel anonymous, in a good way?'),
  (236, 'What is something you would do differently if we lived in the same city?'),
  (237, 'What is a thing that is going better than you expected?'),
  (238, 'What is a thing that is going worse than you expected?'),
  (239, 'What is something you want to have learned by this time next year?'),
  (240, 'What is a piece of your childhood you would like to pass on?'),
  (241, 'What is a piece of your childhood you would not?'),
  (242, 'What is a small ritual you have?'),
  (243, 'What is a thing that always cheers you up?'),
  (244, 'What is something you are ready to let go of?'),
  (245, 'What is a photograph you wish existed?'),
  (246, 'What is a way you have surprised yourself lately?'),
  (247, 'What are you most looking forward to in October?'),
  (248, 'What is a thing you would like us to be braver about?'),
  (249, 'What is a difficult thing you handled well recently?'),
  (250, 'What is a way you like to be told bad news?'),
  (251, 'What is a thing about the future that excites you?'),
  (252, 'What is a thing about the future that scares you?'),
  (253, 'What is something you do that your friends would be surprised by?'),
  (254, 'What is the last thing you looked up out of curiosity?'),
  (255, 'What is a way you are like me?'),
  (256, 'What is a way you are nothing like me?'),
  (257, 'What is a small thing in your home you love?'),
  (258, 'What is a small thing in your home you hate?'),
  (259, 'What is the last conversation that changed your mind?'),
  (260, 'What is a thing you have been generous with that you should protect more?'),
  (261, 'What is a thing you have protected that you could be more generous with?'),
  (262, 'What is the last thing you did for the first time?'),
  (263, 'What is a thing you find genuinely peaceful?'),
  (264, 'What did you dream about recently?'),
  (265, 'What is a small victory from today?'),
  (266, 'What is a way you would like to spend a whole day with me?'),
  (267, 'What is a thing you always forget?'),
  (268, 'What is a thing you never forget?'),
  (269, 'What is the best thing about your closest friend?'),
  (270, 'What is a thing you have been thinking about buying for us?'),
  (271, 'What is something you would like to unlearn?'),
  (272, 'What is a thing that felt impossible a year ago?'),
  (273, 'What is something you notice about yourself when you are stressed?'),
  (274, 'What is something you notice about me when I am stressed?'),
  (275, 'What is a thing you would like to make?'),
  (276, 'What is a way you have been brave this month?'),
  (277, 'What is a thing you would like to be less afraid of?'),
  (278, 'What is the best part of a long flight?'),
  (279, 'What is the worst part of a long flight?'),
  (280, 'What is something you have never done that most people have?'),
  (281, 'What is something you have done that most people have not?'),
  (282, 'What is a piece of music that feels like a place?'),
  (283, 'What do you want people to remember about how you treated them?'),
  (284, 'What is a thing you find hard to be patient with?'),
  (285, 'What is something you have been reading, watching or listening to?'),
  (286, 'What is a way our lives are more similar than they look?'),
  (287, 'What is a small thing that has been bothering you?'),
  (288, 'What is a big thing that has stopped bothering you?'),
  (289, 'What is a thing you would like to do alone?'),
  (290, 'What is a thing you would like to do together that we never do?'),
  (291, 'What is a thing you would defend even though it is objectively bad?'),
  (292, 'What is a thing about being an adult that nobody warned you about?'),
  (293, 'What is a way you have been looked after well?'),
  (294, 'What is a way you have looked after someone well?'),
  (295, 'What is the most interesting thing about your day so far?'),
  (296, 'What is a question you have been sitting with?'),
  (297, 'What is something that made you feel understood recently?'),
  (298, 'What is a thing you would tell me if you knew I would not take it badly?'),
  (299, 'What is a thing that used to scare you and no longer does?'),
  (300, 'What is a place you have only seen in photos?'),
  (301, 'When did you last feel completely unhurried?'),
  (302, 'What is something you would rearrange about your week?'),
  (303, 'What is a small pleasure you had today?'),
  (304, 'What did you put off today, and was it the right call?'),
  (305, 'What is a thing you like about the way you were raised?'),
  (306, 'What is a thing you would keep from this year?'),
  (307, 'What is a thing you would leave behind from this year?'),
  (308, 'What is a way you have grown that is hard to see from the outside?'),
  (309, 'What is something you are doing purely out of habit?'),
  (310, 'What is a way you would like to be challenged?'),
  (311, 'When did someone last make you feel special?'),
  (312, 'What is a thing you find easy that others find hard?'),
  (313, 'What is a thing you find hard that others find easy?'),
  (314, 'What is the most useful thing you own?'),
  (315, 'What is the least useful thing you own and refuse to get rid of?'),
  (316, 'What is a thing you are looking forward to about living in the same place?'),
  (317, 'What is a thing you will miss about this period, once it is over?'),
  (318, 'What is a thing you keep putting on a list and never doing?'),
  (319, 'What is a way you are different at work than at home?'),
  (320, 'What is a thing you overthink?'),
  (321, 'What is a thing you should think about more?'),
  (322, 'What is a compliment about me you would give to someone else?'),
  (323, 'What is a thing you find hard to believe about yourself?'),
  (324, 'What is a thing about us that you are quietly certain of?'),
  (325, 'What is something you would like a second opinion on?'),
  (326, 'When did you last change your routine?'),
  (327, 'What is a thing you like about being tired?'),
  (328, 'What is a thing you want to say yes to more often?'),
  (329, 'What is a small thing you did well today?'),
  (330, 'What is a way we could make this week feel less ordinary?'),
  (331, 'What is a thing you would like to know about my childhood?'),
  (332, 'What is a story about you I have probably heard wrong?'),
  (333, 'What is something happening tomorrow that you are looking forward to?'),
  (334, 'What is a thing you find hopeful right now?'),
  (335, 'What is a thing you have been quietly worrying about?'),
  (336, 'What is the best conversation you have had this month?'),
  (337, 'What is a thing you would like to do less of?'),
  (338, 'What is a thing you would like to do more of?'),
  (339, 'What is a way this distance has taught you something?'),
  (340, 'What is a way this distance has taught you nothing at all?'),
  (341, 'What is a thing that made you think of me today?'),
  (342, 'What do you think we will laugh about in five years?'),
  (343, 'What is a small thing you can do tomorrow that future you will thank you for?'),
  (344, 'What is a thing about your day that you would not put in a message?'),
  (345, 'How would you describe this year so far in one sentence?'),
  (346, 'What is a thing you want to remember about today in ten years?'),
  (347, 'What is a thing you have stopped apologising for?'),
  (348, 'What is a thing you should apologise for less?'),
  (349, 'What is a thing you have never regretted spending money on?'),
  (350, 'What is a thing about me you would not change?'),
  (351, 'What is a thing you would like to plan properly rather than leave to chance?'),
  (352, 'What is a thing you have learned about yourself this year?'),
  (353, 'What is a place in your day where your mind wanders?'),
  (354, 'What is a thing you would like us to argue about less?'),
  (355, 'What is a thing you would like us to talk about more?'),
  (356, 'What is a small thing that felt like a lot today?'),
  (357, 'What is a way you have been lucky?'),
  (358, 'What is a way you have made your own luck?'),
  (359, 'What is a thing you would like to be doing this time next year?'),
  (360, 'What is a thing you are proud of that has nothing to do with work?'),
  (361, 'What is the last thing that made you feel at home?'),
  (362, 'What is a thing you would like to say to me right now, plainly?'),
  (363, 'What is a thing about this year you did not see coming?'),
  (364, 'What is a thing worth doing again next year?')
on conflict (day_index) do update set text = excluded.text;

-- Verify: expect 365.
-- select count(*) from public.lifeos_prompts;
